# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-paginate, jekyll-gist]

# Setup
title:            The Pineapple Rail
tagline:          'A Klamworks site'
description:      'Welcome to the Rail! We are on the express train to new and amazing things!'
url:              http://duncanklam.github.io
baseurl:          /

author:
  name:           'Duncan Klemm'
  url:            https://twitter.com/Klemmchowdah_II

paginate:         5

# Custom vars
version:          v1.0.0

github:
  repo:           https://github.com/DuncanKlam/duncanklam.github.io
