# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-paginate, jekyll-gist]

# Setup
title:            The Pineapple Rail
tagline:          'A Klamworks site'
description:      'Welcome to the Rail! We are on the express train to awesome things! Maintained by <a href="https://twitter.com/Klemmchowdah_II" target="_blank">@Klemmchowdah_II</a>.'
url:              http://duncanklam.github.io
baseurl:          /

author:
  name:           'Duncan Klemm'
  url:            https://twitter.com/Klemmchowdah_II

paginate:         5

# Custom vars
version:          v2.0.2

github:
  repo:           https://github.com/DuncanKlam/duncanklam.github.io
